### ISSUE TITLE
Fehler im Inhaltsverzeichnis

### ISSUE THREAD

**Issue by MeikeRietz** [BLelgemann/malis_aufgabe-T9-1#1]
Hallo Britta,

im Inhaltsverzeichnis ist ein Link zum Unterkapitel "3.3 Opac" gesetzt. Das Unterkapitel taucht aber im Text nicht auf.

LG
Meike

**Comment by BLelgemann** [comment]
Vielen Dank für den Hinweis. Ich nehme den Link raus!

Viele Grüße
Britta
