### ISSUE TITLE
Gendern

### ISSUE THREAD

**Issue by MeikeRietz** [BLelgemann/malis_aufgabe-T9-1#3]
Hallo Britta,

ans Gendern muss ich mich auch immer noch gewöhnen. Meistens sind die Formen richtig, aber auf folgende Stellen kannst du vielleicht nochmal einen Blick werfen:

1. Kapitel 3.1: "...wird den Teilnehmenden" statt "Teilnehmern"

2. Kapitel 3.2: "...Studierende und Lehrende sowie Mitarbeitende" statt "Mitarbeiter"

LG
Meike

**Comment by BLelgemann** [comment]
Ah, danke für den Hinweis! Laut unserer Policy sollen wir Mitarbeiter*innen und Teilnehmer*innen schreiben. Ich ändere das dann entsprechend.

Viele Grüße
Britta
